Update README.md
mc2-center/data-models pull request #52
Opened 2024-01-10 17:43 UTC by aditigopalan

Adding release notes and versioning information to the README

Fixes #(GH issue number)

## Changelog

 - Added ...
 - Removed ...

2024-01-10 18:23 UTC, jaybee84 requested changes
@aditigopalan added a couple of comments, please take a look.

2024-01-10 18:23 UTC, jaybee84 commented on README.md
> +The latest version release is v23.12.1. Moving forward, this repository will adopt <a href="https://semvar.org/" target="_blank"> Semanting Versioning</a>  (SemVar), which provides a standard way of
```suggestion
The version release tag for January 2024 is v23.12.1. Moving forward, this repository will adopt <a href="https://semvar.org/" target="_blank"> Semanting Versioning</a>  (SemVar), which provides a standard way of versioning software based on meaningful changes in functionality.
```

2024-01-10 18:23 UTC, jaybee84 commented on README.md
> +The latest version release is v23.12.1. Moving forward, this repository will adopt <a href="https://semvar.org/" target="_blank"> Semanting Versioning</a>  (SemVar), which provides a standard way of
I added a small edit. Also, the link here is not going to the right place. Could you please check the link?

2024-01-10 20:54 UTC, aditigopalan commented
@jaybee84 done!

2024-01-17 21:55 UTC, jaybee84 approved these changes

2024-01-17 21:56 UTC, merged